### ISSUE TITLE
Expectations for categorical features?

### ISSUE THREAD

**Issue by DataStrategist** [mdneuzerling/exemplar#4]
Hey buddy! I'm working on that same old report, but have found that some of the reported categories have changed a little bit... small stuff.... plural/singular, uppercase/lowercase, and in a few examples, combining two categories. I would like to use this to capture those differences too... what do you think?

A few preliminary ideas:

 - We could mark categorical features as factors, and have factors go through the thingie?
 - the function could have an input where it asks explicitly if any columns values should be stored?
 
 Something like that. What do you think?

**Comment by mdneuzerling** [comment]
I'm not sure about this. Character columns can contain arbitrary string information that doesn't necessarily need to be within a particular range. For example, if I have a data frame with the information of 10,000 people, that might contain 10,000 different addresses, and I don't want to print out code that checks if every value of a new data frame is one of those 10,000 values.

Factors should be used for columns where each value should be one of a small, discrete number of values. In this case, the assertion code does include a range check: 

```r
assertions.factor <- function(x, data_name = "data", ...) {
  level_assertion <- if (is.ordered(x)) {
    expected_levels <- input_character_vector(levels(x))
    glue::glue("identical(levels({data_name}), {expected_levels})")
  } else {
    # in this case order doesn't matter so we sort before comparing
    expected_levels <- input_character_vector(sort(levels(x)))
    glue::glue("identical(sort(levels({data_name})), {expected_levels})")
  }

  c(
    glue::glue("is.factor({data_name})"),
    level_assertion,
    generate_none_missing_assertion(x, data_name),
    generate_uniqueness_assertion(x, data_name)
  )
}
```

If you do have very specific checks --- like each value is capitalised in a certain way or satisfies a certain regex --- then I think that would be up to the user to write those assertions. They could fit neatly into the function that `exemplar` produces.

**Comment by DataStrategist** [comment]
That's amazing... indeed, what I wanted was `assertions.factor`. I actually didn't know that was implemented... I looked at the code before posting, but in the wrong file. 🤦 

Thanks dude.
