### ISSUE TITLE
Not checking for "no rows returned"

### ISSUE THREAD

**Issue by DataStrategist** [mdneuzerling/exemplar#6]
Hi David, hope you've been well.

See the following screenshot. My ETL process failed to pick up the right data, so it returned a correct data rectangle, but with no results. This passed all the validations!

<img width="726" alt="image" src="https://github.com/mdneuzerling/exemplar/assets/8094091/210959d0-26ec-45e4-988b-fa4146cfdbe5">

To avoid against this case, maybe there should be a binary check added that says "there is more than one row in this dataset"? What do you think?

**Comment by mdneuzerling** [comment]
Oh I like that idea! I've added that in the default assertions generated for a data frame, although it can be disabled with `.check_non_empty = FALSE`. It's enabled by default though.
